pipeline {
    agent any
    stages {
		stage('clone') {
			steps {
				script {
					sh 'git clone https://github.com/m1023294/util_repo'
					echo 'clone success'
					javaCiUtility=load 'java/java-ci'
					echo 'load success'
					javaCiUtility.execute();
				}
			}
		}
	}
}